#  This file is part of Mathstreams.
#
#  Copyright (c) 2015  Sohani Academy <developer@sohaniacademy.com>
#
#  Mathstreams is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

security:
    encoders:
         Magnets\MathgymBundle\Entity\User:
           algorithm: bcrypt
           cost: 12
         Symfony\Component\Security\Core\User\User: plaintext
         ajax:
           algorithm: bcrypt
           cost: 4
         
         
    role_hierarchy:
        ROLE_GOLD:        ROLE_USER
        ROLE_ADMIN:       ROLE_GOLD
        ROLE_SU:          [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:        
        users_db:
            entity: { class: MagnetsMathgymBundle:User, property: email}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|console)|css|images|js)/
            anonymous: ~
        
        user_area:
            pattern:  ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: user
                always_use_default_target_path: true
                require_previous_session: false
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:       logout
                target:     index
            switch_user: true
                    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/su, roles: ROLE_SU }
        - { path: ^/gold, roles: ROLE_GOLD }